package cos.bean;

public class Institute {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column institute.institute_id
     *
     * @mbg.generated Sat Jan 08 21:30:11 CST 2022
     */
    private Integer instituteId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column institute.institute_name
     *
     * @mbg.generated Sat Jan 08 21:30:11 CST 2022
     */
    private String instituteName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column institute.institute_id
     *
     * @return the value of institute.institute_id
     *
     * @mbg.generated Sat Jan 08 21:30:11 CST 2022
     */
    public Integer getInstituteId() {
        return instituteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column institute.institute_id
     *
     * @param instituteId the value for institute.institute_id
     *
     * @mbg.generated Sat Jan 08 21:30:11 CST 2022
     */
    public void setInstituteId(Integer instituteId) {
        this.instituteId = instituteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column institute.institute_name
     *
     * @return the value of institute.institute_name
     *
     * @mbg.generated Sat Jan 08 21:30:11 CST 2022
     */
    public String getInstituteName() {
        return instituteName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column institute.institute_name
     *
     * @param instituteName the value for institute.institute_name
     *
     * @mbg.generated Sat Jan 08 21:30:11 CST 2022
     */
    public void setInstituteName(String instituteName) {
        this.instituteName = instituteName;
    }

	@Override
	public String toString() {
		return "Institute [instituteId=" + instituteId + ", instituteName=" + instituteName + "]";
	}
    
}