package cos.bean;

public class Position {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.position_id
     *
     * @mbg.generated Sat Jan 08 00:03:41 CST 2022
     */
    private Integer positionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position.position_name
     *
     * @mbg.generated Sat Jan 08 00:03:41 CST 2022
     */
    private String positionName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.position_id
     *
     * @return the value of position.position_id
     *
     * @mbg.generated Sat Jan 08 00:03:41 CST 2022
     */
    public Integer getPositionId() {
        return positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.position_id
     *
     * @param positionId the value for position.position_id
     *
     * @mbg.generated Sat Jan 08 00:03:41 CST 2022
     */
    public void setPositionId(Integer positionId) {
        this.positionId = positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position.position_name
     *
     * @return the value of position.position_name
     *
     * @mbg.generated Sat Jan 08 00:03:41 CST 2022
     */
    public String getPositionName() {
        return positionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position.position_name
     *
     * @param positionName the value for position.position_name
     *
     * @mbg.generated Sat Jan 08 00:03:41 CST 2022
     */
    public void setPositionName(String positionName) {
        this.positionName = positionName;
    }
}